title: Mzdové výpočty pro studenty
baseURL: https://olgastankova.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-117913155-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Pracovněprávní a mzdové informace.
  authors: Olga Staňková, Tereza Vršková

